# Generated by Django 4.0.5 on 2022-06-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_item_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='activity',
        ),
    ]
