# Generated by Django 4.0.5 on 2022-06-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_remove_item_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
